FROM busybox:latest

WORKDIR /home/

COPY znnd-amd64 /bin/

COPY libznn.so /lib/

RUN <<EOF
mkdir -p /root/.znn
chmod +x /bin/znnd-amd64 
EOF

#COPY config.json /root/.znn

EXPOSE 35995 35996 35997 35998

CMD ["znnd-amd64"]
